### ISSUE TITLE
gets stuck on downloading assets file on mojang

### ISSUE THREAD

**Issue by unnaturalistic** [UltimMC/Launcher#265] opened 2023-02-28 17:30 UTC
### Description of bug

cannot add new version

### Steps to reproduce

click instances
choose version
new instance

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by BabyBoy666** [comment] 2023-02-28 18:44
already posted: https://github.com/UltimMC/Launcher/issues/257#issue-1523069955

**Comment by Neptune650** [comment] 2024-03-09 22:49
Duplicate of #257

**Closed as not planned by Neptune650** 2024-03-09 22:49 UTC
Labels: bug
