### ISSUE TITLE
Ely.by skin not showing up.

### ISSUE THREAD

**Issue by sutacselif** [UltimMC/Launcher#237] opened 2022-09-02 10:19 UTC
### Operating System

_Windows_

### Description of bug

i use an Ely.by account for one reason only: for the skin, 
but that **immediately** becomes useless because the skin i'm using in my Ely.by account doesn't show up. 
and yes, i tried to use the "Upload Skin" feature, but a popup shows up saying "Failed to upload skin!"

### Steps to reproduce

- Make an Ely.by account
- Use a skin in that account
- Launch UltimMC
- Click on Profiles in the top right corner
- Click on Manage Accounts
- Click on Add Account
- Log in

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Erfankazi** [comment] 2022-09-08 14:58
It isn't work

**Comment by jaredmontoya** [comment] 2022-09-15 16:13
can confirm that same issue is present on linux

**Comment by t0pology** [comment] 2022-10-04 02:52
also running into the same issues on windows :(

**Comment by cesarlmt27** [comment] 2022-10-05 17:33
I have the same problem. I'm using Windows.

**Comment by Miyoni** [comment] 2022-11-01 22:22
This worked for me:

1. Download old UltimMC.exe from [here](https://github.com/UltimMC/Launcher/issues/149#issuecomment-1019708115)
2. Copy UltimMC.exe from the UltimMC install location to somewhere else (e.g. another folder) so you can move it back later
3. Move newly downloaded UltimMC.exe into install location
4. Run UltimMC and log into your Ely.by account using your e-mail and password. You will know that it worked when you see the head of your skin and your username in the top right corner
5. Close UltimMC, delete UltimMC.exe and drag the other UltimMC.exe you copied earlier back into the install location.

**Comment by sutacselif** [comment] 2022-11-02 08:58
this surprisingly worked for me, thanks, but this issue really needs to be resolved though.

**Comment by N1ckn1ght** [comment] 2022-11-18 09:33
Yeah, the issue is not completed. Temporary solution works, but why this issue is closed?

**Comment by sutacselif** [comment] 2022-11-18 14:32
sorry for the inconvenience, i didn't sleep well that night, so i may have closed the issue by accident. here's the link to the new issue: https://github.com/UltimMC/Launcher/issues/249

**Comment by sutacselif** [comment] 2022-11-18 14:47
> Yeah, the issue is not completed. Temporary solution works, but why this issue is closed 

probably didn't sleep well that night, thanks for pointing it out.

**Comment by Fr4Ckt3r** [comment] 2022-11-29 18:18
> This worked for me:
> 
>     1. Download old UltimMC.exe from [here](https://github.com/UltimMC/Launcher/issues/149#issuecomment-1019708115)
> 
>     2. Copy UltimMC.exe from the UltimMC install location to somewhere else (e.g. another folder) so you can move it back later
> 
>     3. Move newly downloaded UltimMC.exe into install location
> 
>     4. Run UltimMC and log into your Ely.by account using your e-mail and password. You will know that it worked when you see the head of your skin and your username in the top right corner
> 
>     5. Close UltimMC, delete UltimMC.exe and drag the other UltimMC.exe you copied earlier back into the install location.

I've logged in, but skin doesn't show up in-game.

**Comment by CamoeLMAO** [comment] 2022-11-30 20:01
> 

worked for me! even though its a temporary fix, i really appreciate it!

**Comment by CamoeLMAO** [comment] 2022-12-01 17:48
> This worked for me:
> 
> 1. Download old UltimMC.exe from [here](https://github.com/UltimMC/Launcher/issues/149#issuecomment-1019708115)
> 2. Copy UltimMC.exe from the UltimMC install location to somewhere else (e.g. another folder) so you can move it back later
> 3. Move newly downloaded UltimMC.exe into install location
> 4. Run UltimMC and log into your Ely.by account using your e-mail and password. You will know that it worked when you see the head of your skin and your username in the top right corner
> 5. Close UltimMC, delete UltimMC.exe and drag the other UltimMC.exe you copied earlier back into the install location.

why cant i just use the old exe?

**Comment by Miyoni** [comment] 2022-12-01 20:32
> why cant i just use the old exe?

You could technically use the old .exe, I think? The update window that pops up every time you launch UltimMC when you use it kinda annoyed me, though lol. And I'm not sure if using an older .exe could maybe somehow cause issues so I prefer to use the newest one.

**Comment by CamoeLMAO** [comment] 2022-12-02 08:02
> 



> > why cant i just use the old exe?
> 
> You could technically use the old .exe, I think? The update window that pops up every time you launch UltimMC when you use it kinda annoyed me, though lol. And I'm not sure if using an older .exe could maybe somehow cause issues so I prefer to use the newest one.

ah okay, thanks

**Comment by spytaspund** [comment] 2023-05-01 18:17
> 

same problem. Skin avatar is showing up, but in game skin does not showing.

**Comment by Neptune650** [comment] 2024-03-12 02:15
![2024-03-11_21 15 23](https://github.com/UltimMC/Launcher/assets/62727185/84daa79c-fcbd-4913-9337-aef0e7bb9645)
Fixed with the latest commit, please update.

**Closed as completed by Neptune650** 2024-03-12 02:15 UTC
Labels: bug
