### ISSUE TITLE
Error while runing launcher on windows 10 home

### ISSUE THREAD

**Issue by daeeros** [UltimMC/Launcher#338] opened 2024-03-11 15:13 UTC
### Description of bug

Faulting application name: UltimMC.exe, version: 1.0.0.0, timestamp: 0x09e72940
Faulting module name: UltimMC.exe, version: 1.0.0.0, timestamp: 0x09e72940
Exception code: 0xc0000005
Error offset: 0x0038432f
Faulting process id: 0x1e0c
Faulting application start time: 0x01da73c5ceca9b5a
Faulting application path: D:\UltimMC\UltimMC.exe
Faulting module path: D:\UltimMC\UltimMC.exe
Report id: cc59c634-8636-4a03-9004-77ac548215d2
Faulting package full name:
Application code associated with the faulty package:

### Steps to reproduce

Install clear windows 10 home x64, download launcher and try to run

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Neptune650** [comment] 2024-03-11 22:28
Duplicate of #335

**Closed as not planned by Neptune650** 2024-03-11 22:28 UTC
Labels: bug
